package com.serranoie.app.core.navigation

enum class Screen {
    HOME,
    LOADING,
    ONBOARDING,
    WELCOME,
    AUTH,
    LOGIN,
    REGISTER,
    FORGOT_PASSWORD,
    SETTINGS,
    ABOUT,
    CHAT,
    EXPENSES,
    ADD_EXPENSE,
    EXPENSE_DETAILS,
    ITINERARY,
    ADD_ITINERARY,
    EDIT_ITINERARY,
    TRIP_SETTINGS,
    TRIP_INFO,
    TRAVEL_LIST,
    CREATE_TRAVEL,
    JOIN_TRIP,
    CAMERA_SCANNER,
}
